"""Add percentiles and std_dev to ratios table

Revision ID: 54ca4f3a91d5
Revises: 
Create Date: 2026-05-28 10:51:30.857124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ca4f3a91d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratios', sa.Column('percentil_25', sa.Float(), nullable=True))
    op.add_column('ratios', sa.Column('percentil_75', sa.Float(), nullable=True))
    op.add_column('ratios', sa.Column('std_dev', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratios', 'std_dev')
    op.drop_column('ratios', 'percentil_75')
    op.drop_column('ratios', 'percentil_25')
    # ### end Alembic commands ###
